### PR TITLE
Fix compile-time warnings with strict prototypes enabled. Fixes #208

### LINKED ISSUE #208: Compile-time warnings with strict prototypes enabled
Adding `-Wstrict-prototypes` to CFLAGS results in a number of warnings such as:

```
/path/to/libxlsxwriter/include/xlsxwriter/relationships.h:50:41: warning: this function declaration
      is not a prototype [-Wstrict-prototypes]
lxw_relationships *lxw_relationships_new();
```

Since C89, functions that take no arguments are supposed to be prototyped as `int function(void);` rather than `int function();`. A quick grep shows a number of non-conforming prototypes:

```
$ grep '();$' include/*/*.h
include/xlsxwriter/app.h:lxw_app *lxw_app_new();
include/xlsxwriter/chartsheet.h:lxw_chartsheet *lxw_chartsheet_new();
include/xlsxwriter/content_types.h:lxw_content_types *lxw_content_types_new();
include/xlsxwriter/core.h:lxw_core *lxw_core_new();
include/xlsxwriter/custom.h:lxw_custom *lxw_custom_new();
include/xlsxwriter/drawing.h:lxw_drawing *lxw_drawing_new();
include/xlsxwriter/format.h:lxw_format *lxw_format_new();
include/xlsxwriter/relationships.h:lxw_relationships *lxw_relationships_new();
include/xlsxwriter/shared_strings.h:lxw_sst *lxw_sst_new();
include/xlsxwriter/styles.h:lxw_styles *lxw_styles_new();
include/xlsxwriter/theme.h:lxw_theme *lxw_theme_new();
```

Should be an easy fix. I'd recommend adding `-Wstrict-prototypes` to the default build options to ensure compliance in the future.

### PR DESCRIPTION
**Pull request by evanmiller**
The C standard (and `-Wstrict-prototypes`) requires that functions which take no arguments be declared as foobar(void) instead of foobar().

### CODE REVIEW

File: include/xlsxwriter/chartsheet.h [hunk 1]
```diff
@@ -524,7 +524,7 @@ lxw_error chartsheet_set_footer_opt(lxw_chartsheet *chartsheet,
                                     const char *string,
                                     lxw_header_footer_options *options);
 
-lxw_chartsheet *lxw_chartsheet_new();
+lxw_chartsheet *lxw_chartsheet_new(void);
```
Comment (jjochen) [inline include/xlsxwriter/chartsheet.h]: I think this should not be `void` but `lxw_worksheet_init_data *init_data`. See here:
https://github.com/jmcnamara/libxlsxwriter/blob/8d50d03b65db6382436156426474d9f16fe90471/src/chartsheet.c#L28

**Comment by jjochen** [comment]
@evanmiller Your tests are failing because [here](https://github.com/jmcnamara/libxlsxwriter/blob/2bdfae296c743be04ced47940ad64d8c7af4d5f8/test/unit/chartsheet/test_chartsheet.c#L33) `NULL` is passed to `lxw_drawing_new`. 
It should be `lxw_drawing_new()`.

**Comment by evanmiller** [comment]
I have merged @jjochen’s changes and the tests (except for tea, which I don’t see any output for) are passing.

**Comment by jmcnamara** [comment]
> (except for tea, which I don’t see any output for

You can ignore any failures apart from Travis. That is the main one that I care about.

Can you rebase this into one commit, or at most 2, one for you and one for @jjochen. Also remove the "Fixes xxx" from the title and move it to the body of the commit.

If you can't, or don't have time, I can do these changes offline with a rebase but I will have to do it from the commandline and separate from this PR and that will take a bit longer.

**Comment by evanmiller** [comment]
I have limited computer access at the moment and am unable to perform a rebase. Thanks.

**Comment by jmcnamara** [comment]
Ok. In the end I just went with the simplest and fastest option and squashed the commits in the UI.

Thanks for you help to both of you. This is merged now.
